### ISSUE TITLE
login nicht erfolgreich (500)

### ISSUE THREAD

**Issue by melfja** [maplesteve/swaggertalk#18]
Registrierung klappte, aber direkt danach nicht das login
beim drücken auf den 'Anmelden' button kommt http Fehler 500, aber keinerlei Fehlermeldung für den Nutzer.

<img width="1280" alt="bildschirmfoto 2017-03-23 um 07 25 16" src="https://cloud.githubusercontent.com/assets/26618476/24235098/ee8b7d24-0f9b-11e7-9980-1ad7849bba36.png">

**Comment by maplesteve** [comment]
vgl. #19
