### ISSUE TITLE
Registrierung: "undefined is not an object"

### ISSUE THREAD

**Issue by melfja** [maplesteve/swaggertalk#19]
hab mich ein weiteres mal registriert - diesmal mit Fehlerconsole.
Für den Nutzer ist kein Fehler erkennbar. 

<img width="1280" alt="bildschirmfoto 2017-03-23 um 07 51 53" src="https://cloud.githubusercontent.com/assets/26618476/24235493/d362fac0-0f9d-11e7-89e6-80fa5db50e11.png">

**Comment by melfja** [comment]
kommt auch bei längeren logins und längeren passwörtern

**Comment by maplesteve** [comment]
In `/js/models/User.js`: `pwdHashForNewPassword` vs. `pwdHash`. Das temporäre Passwort wird (absichtlich) nicht im model gespeichert - was `pwdHash` aber erwartet...
