### ISSUE TITLE
Wert im kommentar Badge auf Ebene Revision falsch

### ISSUE THREAD

**Issue by melfja** [maplesteve/swaggertalk#22]
Es wird 2 angezeigt obwohl keine Kommentare vorhanden sind

<img width="1280" alt="bildschirmfoto 2017-03-23 um 13 54 42" src="https://cloud.githubusercontent.com/assets/26618476/24248640/7ce7588e-0fd0-11e7-9092-521192aa409a.png">

**Comment by maplesteve** [comment]
Ja, verstanden. Die Zahl in der Badge ist richtig, aber eine race condition hat die Anzeige (manchmal) verhindert.

**Comment by maplesteve** [comment]
fix mit 249b315637598534bff21375103d1e365aba556d
