### ISSUE TITLE
major: Kommentar wird nicht gespeichert

### ISSUE THREAD

**Issue by melfja** [maplesteve/swaggertalk#23]
kann Kommentare schreiben - beim Drücken des 'Ok' Buttons  (newCommentButton) passiert aber nichts.
Die Kommentare bleiben auf der Seite, werden offensichtlich aber nicht gespeichert.
<img width="1280" alt="bildschirmfoto 2017-03-23 um 14 00 41" src="https://cloud.githubusercontent.com/assets/26618476/24248822/4160ee46-0fd1-11e7-9ec6-170dcb640be8.png">

**Comment by melfja** [comment]
es ist keinerlei Netzaktivität erkennbar.  Ich hätte beim drücken des Button ein POST comment erwartet

**Comment by maplesteve** [comment]
Kann auch nicht funktionieren, wenn der Button mit keiner Methode verknüpft ist... :-(

**Comment by maplesteve** [comment]
fix mit 249b315637598534bff21375103d1e365aba556d
