### ISSUE TITLE
Bug: neu angelegte API enthält Endpunkte die nicht im swagger existieren

### ISSUE THREAD

**Issue by melfja** [maplesteve/swaggertalk#38]
habe eine neue API angelegt 
eine neue Revision
ein swagger hochgeladen:

erwarte  /v1/documents/legitimation/ upload   

bekomme jede menge Endpunkte, die nicht im swagger stehen:
https://swaggertalk.esch.cc/revision.html?9651f2a9-2688-11e7-98c9-f751c8312ad3/c708a6e4-2688-11e7-ac61-5d6ed45e0f20

dafür **fehlen die erwarteten Endpunkte** !

**Comment by melfja** [comment]
habe eine andere API geöffnet (repair)
und bekomme dort ebenfalls Endpunkte angezeigt, die nicht zu repair gehören.
Meist sind die Endpunkte leer. 
Wenn sie nicht leer sind, passt der angezeigte Inhalt nicht zur Überschrift.  Beispiel:
bei drücken auf 'PUT /v1/marketingPermit/permits/{permitId}/documentId'
<img width="715" alt="bildschirmfoto 2017-04-21 um 14 09 39" src="https://cloud.githubusercontent.com/assets/26618476/25276807/45dac26c-269c-11e7-8a06-0b1f7b90725b.png">

wird aber angezeigt 'deliveryAdress'
<img width="899" alt="bildschirmfoto 2017-04-21 um 14 10 58" src="https://cloud.githubusercontent.com/assets/26618476/25276829/62f1db9c-269c-11e7-8caf-ff0b0c78aca1.png">

**Comment by maplesteve** [comment]
Die in der API definierte DB-Abfrage war 'dumm' (Scan statt Query). Gefixt.
